# Generated by Django 5.0.7 on 2024-07-11 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, verbose_name='Name')),
                ('video', models.FileField(upload_to='video', verbose_name='Upload video')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('user_likes', models.ManyToManyField(blank=True, help_text='User can like once', null=True, to=settings.AUTH_USER_MODEL, verbose_name='Like by')),
            ],
        ),
    ]
